/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-12-18 05:02:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Dam_005fFrontend_005fWorkFile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class frontPage_005fver1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/DamStyle.css?after\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/siderbar.css?after\" />\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <script\r\n");
      out.write("      type=\"text/javascript\"\r\n");
      out.write("      src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js\"\r\n");
      out.write("      integrity=\"sha512-QEiC894KVkN9Tsoi6+mKf8HaCLJvyA6QIRzY5KrfINXYuP9NxdIkRQhGq3BZi0J4I7V5SidGM3XUQ5wFiMDuWg==\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("   <title>Dam Project</title>\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav class=\"navbar\">\r\n");
      out.write("        <h3>Dam Dashboard (JSP)</h3>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!--  ■■■좌측 사이드바 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ -->\r\n");
      out.write("    <nav class=\"main-menu\">\r\n");
      out.write("      <img\r\n");
      out.write("        class=\"icon_sun\"\r\n");
      out.write("        src=\"https://blog.kakaocdn.net/dn/61zMy/btrh7wm0fCv/IgGApTNnNkY2Y9UVKKWjbK/img.png\"\r\n");
      out.write("        alt=\"icon_sun\"\r\n");
      out.write("        style=\"width: 60%; max-width: 100px\"\r\n");
      out.write("      />\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">\r\n");
      out.write("            <i class=\"fa fa-laptop fa-2x\"></i>\r\n");
      out.write("            <span class=\"nav-text\" id=\"btn1\"> Dam 1 </span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"has-subnav\">\r\n");
      out.write("          <a href=\"#\">\r\n");
      out.write("            <i class=\"fa fa-laptop fa-2x\"></i>\r\n");
      out.write("            <span class=\"nav-text\"> Dam 2 </span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"has-subnav\">\r\n");
      out.write("          <a href=\"#\">\r\n");
      out.write("            <i class=\"fa fa-laptop fa-2x\"></i>\r\n");
      out.write("            <span class=\"nav-text\"> Dam 3 </span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"has-subnav\">\r\n");
      out.write("          <a href=\"#\">\r\n");
      out.write("            <i class=\"fa fa-laptop fa-2x\"></i>\r\n");
      out.write("            <span class=\"nav-text\"> Dam 4 </span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"#\">\r\n");
      out.write("            <i class=\"fa fa-laptop fa-2x\"></i>\r\n");
      out.write("            <span class=\"nav-text\"> Dam 5 </span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■좌측 사이드바 ■■■ -->\r\n");
      out.write("    <!--  원래 좌 중 우로 구역을 나눴으나 좌, 우를 지움 -->\r\n");
      out.write("    <div class=\"TotalPage border_red_power_dot\">\r\n");
      out.write("      <!-- 왼쪽 구역 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ -->\r\n");
      out.write("\r\n");
      out.write("      <!--  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 왼쪽 구역-->\r\n");
      out.write("      <!-- 중앙 구역 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ -->\r\n");
      out.write("      <div class=\"middle_page border_blue_dot\">\r\n");
      out.write("        <div class=\"sensor_area border_yellow_dot\">\r\n");
      out.write("          <div class=\"sensor_block externalCard_black\" id=\"water_level\">\r\n");
      out.write("            <div class=\"sensor_name\">댐 이름</div>\r\n");
      out.write("            <div class=\"sensor_data\" id=\"DAM_NAME\">댐 n</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sensor_block externalCard_black\" id=\"water_level\">\r\n");
      out.write("            <div class=\"sensor_name\">현재 근무자</div>\r\n");
      out.write("            <div class=\"sensor_data\" id=\"WORK_NMPR\">1972 명</div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sensor_block externalCard\" id=\"water_level\">\r\n");
      out.write("            <div class=\"sensor_name\">수위 센서</div>\r\n");
      out.write("            <div class=\"sensor_data\" id=\"WATER_LEVEL\">12345</div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"sensor_block externalCard\" id=\"light_level\">\r\n");
      out.write("            <div class=\"sensor_name\">조도 센서</div>\r\n");
      out.write("            <div class=\"sensor_data\" id=\"LIGHT\">67890</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!--  차트가 들어갈 영역 ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ -->\r\n");
      out.write("        <div class=\"chart_area border_blue_dot\">\r\n");
      out.write("          <!-- <button id=\"addData\">First Out * Last In</button> -->\r\n");
      out.write("          <div class=\"chart-container border_red_dot\">\r\n");
      out.write("            <canvas id=\"line1\" class=\"border_pink_dot\"></canvas>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ차트가 들어갈 영역 -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 중앙 구역-->\r\n");
      out.write("      <!-- 오른쪽 구역 ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ -->\r\n");
      out.write("      <!-- <div class=\"right_page border_red_dot\">\r\n");
      out.write("        <img\r\n");
      out.write("          class=\"icon_sun\"\r\n");
      out.write("          src=\"https://blog.kakaocdn.net/dn/61zMy/btrh7wm0fCv/IgGApTNnNkY2Y9UVKKWjbK/img.png\"\r\n");
      out.write("          alt=\"icon_sun\"\r\n");
      out.write("          style=\"width: 60%; max-width: 100px\"\r\n");
      out.write("        />\r\n");
      out.write("\r\n");
      out.write("        <div class=\"current_worker\">\r\n");
      out.write("          <span class=\"icon_worker\">\r\n");
      out.write("            <svg\r\n");
      out.write("              xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              viewBox=\"0 0 24 24\"\r\n");
      out.write("              fill=\"currentColor\"\r\n");
      out.write("              class=\"w-6 h-6\"\r\n");
      out.write("            >\r\n");
      out.write("              <path\r\n");
      out.write("                fill-rule=\"evenodd\"\r\n");
      out.write("                d=\"M18.685 19.097A9.723 9.723 0 0021.75 12c0-5.385-4.365-9.75-9.75-9.75S2.25 6.615 2.25 12a9.723 9.723 0 003.065 7.097A9.716 9.716 0 0012 21.75a9.716 9.716 0 006.685-2.653zm-12.54-1.285A7.486 7.486 0 0112 15a7.486 7.486 0 015.855 2.812A8.224 8.224 0 0112 20.25a8.224 8.224 0 01-5.855-2.438zM15.75 9a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z\"\r\n");
      out.write("                clip-rule=\"evenodd\"\r\n");
      out.write("              />\r\n");
      out.write("            </svg>\r\n");
      out.write("          </span>\r\n");
      out.write("          <span class=\"current_worker_num\">N 명 근무 중</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div> -->\r\n");
      out.write("      <!--  ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 오른쪽 구역-->\r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/AreaChart.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
